### PR TITLE
Fixed some grammar mistakes

### PR DESCRIPTION
**Pull request by ptrcortes**

### CODE REVIEW

**Comment by RinaDev-xyz** [comment]
Hey there,

Thanks for the fixes, I will merge now. I will push this in the next release!

**Review by RinaDev-xyz — APPROVED** [review]

**Comment by ptrcortes** [comment]
awesome, I just switched from the official version.. thanks for continuing development :)

**Comment by RinaDev-xyz** [comment]
No worries, if you have issues feel free to report them!

**Comment by RinaDev-xyz** [comment]
Now in the latest release for Blender 3.6 and Blender 4.1 :)

**Pull request merged**
